### ISSUE TITLE
RFE: please add pytest support

### ISSUE THREAD

**Issue by kloczek** [stamparm/pcapy-ng#8]
Looks like pytest is not able to find any units
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pcapy-ng-1.0.9-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pcapy-ng-1.0.9-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pcapy-ng-1.0.9
collected 0 items

========================================================================== no tests ran in 0.01s ===========================================================================
```

**Comment by kloczek** [comment]
Current tests are not working ATM ..
```console
+ cd tests
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pcapy-ng-1.0.9-2.fc35.x86_64//usr/lib64/python3.8/site-packages
+ /usr/bin/python3 pcapytests.py
testBPFFilter (__main__.TestPcapy)
#3 test offline BPFFilter ... ok
testClose (__main__.TestPcapy)
#7 Test the close method ... ok
testContextManager (__main__.TestPcapy)
#8 Test the context manager support ... ok
testEOFValue (__main__.TestPcapy)
#2 empty string is returned as packet body at end of file ... FAIL
testPacketDumper (__main__.TestPcapy)
#6 test that the dumper writes correct payload ... ok
testPacketHeaderRefCount (__main__.TestPcapy)
#1: when next() creates a pkthdr it makes one extra reference ... ok
test_get_bpf (__main__.TestPcapy) ... ok

======================================================================
FAIL: testEOFValue (__main__.TestPcapy)
#2 empty string is returned as packet body at end of file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pcapytests.py", line 52, in testEOFValue
    self.assertEqual(refNone, sys.getrefcount(None))
AssertionError: 7043 != 7042

----------------------------------------------------------------------
Ran 7 tests in 0.002s
```

**Comment by kloczek** [comment]
Updated current pytest output:
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pcapy-ng-1.0.9-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pcapy-ng-1.0.9-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network' pcapytests.py
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pcapy-ng-1.0.9
collected 0 items / 1 error

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/pcapytests.py _____________________
/usr/lib/python3.8/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
/usr/lib/python3.8/site-packages/_pytest/runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/usr/lib/python3.8/site-packages/_pytest/python.py:536: in collect
    self._inject_setup_module_fixture()
/usr/lib/python3.8/site-packages/_pytest/python.py:550: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
/usr/lib/python3.8/site-packages/_pytest/python.py:315: in obj
    self._obj = obj = self._getobj()
/usr/lib/python3.8/site-packages/_pytest/python.py:533: in _getobj
    return self._importtestmodule()
/usr/lib/python3.8/site-packages/_pytest/python.py:622: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
pcapytests.py:172: in <module>
    sys.exit(1)
E   SystemExit: 1
------------------------------- Captured stderr --------------------------------
testBPFFilter (pcapytests.TestPcapy)
#3 test offline BPFFilter ... ok
testClose (pcapytests.TestPcapy)
#7 Test the close method ... ok
testContextManager (pcapytests.TestPcapy)
#8 Test the context manager support ... ok
testEOFValue (pcapytests.TestPcapy)
#2 empty string is returned as packet body at end of file ... FAIL
testPacketDumper (pcapytests.TestPcapy)
#6 test that the dumper writes correct payload ... ok
testPacketHeaderRefCount (pcapytests.TestPcapy)
#1: when next() creates a pkthdr it makes one extra reference ... ok
test_get_bpf (pcapytests.TestPcapy) ... ok

======================================================================
FAIL: testEOFValue (pcapytests.TestPcapy)
#2 empty string is returned as packet body at end of file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/pcapy-ng-1.0.9/tests/pcapytests.py", line 52, in testEOFValue
    self.assertEqual(refNone, sys.getrefcount(None))
AssertionError: 14728 != 14725

----------------------------------------------------------------------
Ran 7 tests in 0.002s

FAILED (failures=1)
=========================== short test summary info ============================
ERROR pcapytests.py - SystemExit: 1
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.22s ===============================
```
</details>
